applications:
  - name: django-app
    namespace: django
    repoURL: https://github.com/PiotrJasinski1995/goit-devops-charts.git
    targetRevision: final-project
    path: charts/django-app

repositories: []
